### ISSUE TITLE
Issue with mamba-2.8b-hf

### ISSUE THREAD

**Issue by joelburget** [Phylliida/MambaLens#5]
Hi there, I tried running my code at https://github.com/joelburget/mamba-sae but got the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 541, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/mamba-sae/hyperparam_sweep.py", line 72, in <module>
    sae = SAETrainingRunner(cfg).run()
  File "/usr/local/lib/python3.10/dist-packages/sae_lens/sae_training_runner.py", line 57, in __init__
    self.model = load_model(
  File "/usr/local/lib/python3.10/dist-packages/sae_lens/load_model.py", line 39, in load_model
    HookedMamba.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 562, in from_pretrained
    cfg, state_dict = get_converted_model_from_hf(pretrained_model_name=pretrained_model_name, device=device)
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 60, in get_converted_model_from_hf
    state_dict = load_state_dict_hf(pretrained_model_name, device=device)
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 55, in load_state_dict_hf
    return torch.load(resolved_archive_file, weights_only=True, map_location=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 450, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in __init__
    _check_seekable(buffer)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 544, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 537, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

We can make it more informative by setting `_raise_exceptions_for_missing_entries=True`. Then the error is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/state-spaces/mamba-2.8b-hf/resolve/main/pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1295, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 388, in _request_wrapper
    hf_raise_for_status(response)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 417, in hf_raise_for_status
    raise _format(EntryNotFoundError, message, response) from e
huggingface_hub.errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66fb67c4-59d1005f1441150f058d058e;623974c7-21e4-4105-bf8b-f98d12cf6614)

Entry Not Found for url: https://huggingface.co/state-spaces/mamba-2.8b-hf/resolve/main/pytorch_model.bin.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/mamba-sae/hyperparam_sweep.py", line 72, in <module>
    sae = SAETrainingRunner(cfg).run()
  File "/usr/local/lib/python3.10/dist-packages/sae_lens/sae_training_runner.py", line 57, in __init__
    self.model = load_model(
  File "/usr/local/lib/python3.10/dist-packages/sae_lens/load_model.py", line 39, in load_model
    HookedMamba.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 562, in from_pretrained
    cfg, state_dict = get_converted_model_from_hf(pretrained_model_name=pretrained_model_name, device=device)
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 60, in get_converted_model_from_hf
    state_dict = load_state_dict_hf(pretrained_model_name, device=device)
  File "/usr/local/lib/python3.10/dist-packages/mamba_lens/HookedMamba.py", line 52, in load_state_dict_hf
    resolved_archive_file = cached_file(model_name, WEIGHTS_NAME)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 459, in cached_file
    raise EnvironmentError(
OSError: state-spaces/mamba-2.8b-hf does not appear to have a file named pytorch_model.bin. Checkout 'https://huggingface.co/state-spaces/mamba-2.8b-hf/tree/main' for available files.
```

I'm not familiar with this way of using `cached_file` so I'm not sure the most robust way to make this work.

**Comment by joelburget** [comment]
It looks like this was because I used `mamba-2.8b-hf` instead of `mamba-2.8b`
